In [21]:
import pandas as pd
import numpy as np


In [2]:
df=pd.read_csv("spam_ham_dataset.csv")
df.head()

Unnamed: 0 label                                               text  \
0         605   ham  Subject: enron methanol ; meter # : 988291\nth...   
1        2349   ham  Subject: hpl nom for january 9 , 2001\n( see a...   
2        3624   ham  Subject: neon retreat\nho ho ho , we ' re arou...   
3        4685  spam  Subject: photoshop , windows , office . cheap ...   
4        2030   ham  Subject: re : indian springs\nthis deal is to ...   

   label_num  
0          0  
1          0  
2          0  
3          1  
4          0

In [5]:
df.label.value_counts()

ham     3672
spam    1499
Name: label, dtype: int64

In [6]:
df['spam']=df['label'].apply(lambda x: 1 if x=='spam' else 0)

In [7]:
df.head()

Unnamed: 0 label                                               text  \
0         605   ham  Subject: enron methanol ; meter # : 988291\nth...   
1        2349   ham  Subject: hpl nom for january 9 , 2001\n( see a...   
2        3624   ham  Subject: neon retreat\nho ho ho , we ' re arou...   
3        4685  spam  Subject: photoshop , windows , office . cheap ...   
4        2030   ham  Subject: re : indian springs\nthis deal is to ...   

   label_num  spam  
0          0     0  
1          0     0  
2          0     0  
3          1     1  
4          0     0

In [9]:
def get_spam_number(x):
    if x=='spam':
       return 1
    else:
       return 0
    

In [10]:
df.head()

Unnamed: 0 label                                               text  \
0         605   ham  Subject: enron methanol ; meter # : 988291\nth...   
1        2349   ham  Subject: hpl nom for january 9 , 2001\n( see a...   
2        3624   ham  Subject: neon retreat\nho ho ho , we ' re arou...   
3        4685  spam  Subject: photoshop , windows , office . cheap ...   
4        2030   ham  Subject: re : indian springs\nthis deal is to ...   

   label_num  spam  
0          0     0  
1          0     0  
2          0     0  
3          1     1  
4          0     0

In [18]:
!pip install scikit-learn 

Defaulting to user installation because normal site-packages is not writeable
  Obtaining dependency information for scikit-learn from https://files.pythonhosted.org/packages/b9/14/b37b415be8179dff311fea26d1cedf59be2d79441486409c1bf8fde63085/scikit_learn-1.4.0-1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Obtaining dependency information for joblib>=1.2.0 from https://files.pythonhosted.org/packages/10/40/d551139c85db202f1f384ba8bcf96aca2f329440a844f924c8a0040b6d02/joblib-1.3.2-py3-none-any.whl.metadata
  Obtaining dependency information for threadpoolctl>=2.0.0 from https://files.pythonhosted.org/packages/81/12/fd4dea011af9d69e1cad05c75f3f7202cdcbeac9b712eea58ca779a72865/threadpoolctl-3.2.0-py3-none-any.whl.metadata
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.2/12.2 MB 2.1 MB/s eta 0:00:00m eta 0:00:010:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.2/302.2 kB 5.0 MB/s eta 0:00:00 MB/s eta 0:00:01


In [20]:
import sklearn
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.text,df.spam,test_size=0.2)

In [22]:
X_train.shape

(4136,)

In [23]:
X_test.shape


(1035,)

In [24]:
type(X_train)

pandas.core.series.Series

In [25]:
X_train[:4]

2257    Subject: california energy crisis\ncalifornia ...
3138    Subject: erich call the doctor .\nthe secret o...
311     Subject: eastrans nomination change effective ...
1711    Subject: hpl nominations for march 31 , 2001 a...
Name: text, dtype: object

In [26]:
y_train[:4]

2257    0
3138    1
311     0
1711    0
Name: spam, dtype: int64

In [27]:
from sklearn.feature_extraction.text import CountVectorizer
v=CountVectorizer()
X_train_cv=v.fit_transform(X_train.values)
X_train_cv

<4136x45430 sparse matrix of type '<class 'numpy.int64'>'
	with 367822 stored elements in Compressed Sparse Row format>

In [28]:
X_train_cv.toarray()[:2][0]


array([0, 0, 0, ..., 0, 0, 0])

In [29]:
X_train_cv.shape

(4136, 45430)

In [30]:
dir(v)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_

In [31]:
v.vocabulary_

{'subject': 39409,
 'california': 10005,
 'energy': 17029,
 'crisis': 13403,
 'power': 33035,
 'has': 21345,
 'generated': 19967,
 'heated': 21521,
 'debate': 14179,
 'over': 31157,
 'the': 40573,
 'last': 25825,
 'several': 37342,
 'months': 28867,
 'unfortunately': 42145,
 'this': 40678,
 'more': 28908,
 'heat': 21520,
 'than': 40550,
 'light': 26308,
 'we': 43647,
 'want': 43490,
 'you': 45009,
 'to': 41009,
 'know': 25382,
 'what': 43837,
 'facts': 18123,
 'are': 6429,
 'and': 5883,
 'doing': 15592,
 'about': 4392,
 'please': 32620,
 'spend': 38651,
 'few': 18472,
 'minutes': 28500,
 'reading': 34657,
 'following': 19035,
 'overview': 31217,
 'on': 30700,
 'situation': 37947,
 'our': 31095,
 'position': 32930,
 'issues': 24062,
 'happened': 21259,
 'in': 23078,
 'source': 38503,
 'of': 30483,
 'current': 13657,
 'problem': 33417,
 'is': 24006,
 'as': 6619,
 'straightforward': 39227,
 'supply': 39631,
 'demand': 14494,
 'economy': 16390,
 'grew': 20760,
 '29': 1448,
 'percent': 3190

In [33]:
X_train_np= X_train_cv.toarray()
X_train_np[:4]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [4, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [35]:
#to find where the email is spam
np.where(X_train_np[0]!=0)

(array([  248,   986,  1206,  1448,  1932,  4370,  4392,  4449,  4690,
         4749,  4759,  4821,  4869,  5089,  5225,  5240,  5478,  5530,
         5605,  5620,  5774,  5783,  5826,  5883,  6290,  6429,  6556,
         6619,  6729,  6826,  6934,  7112,  7141,  7159,  7381,  7478,
         7621,  7756,  7819,  7866,  7906,  7927,  7957,  8190,  8273,
         8361,  8527,  8548,  8987,  9587,  9726,  9741,  9787,  9842,
         9875, 10005, 10096, 10157, 10193, 10218, 10232, 10529, 10924,
        11569, 11573, 12094, 12193, 12229, 12230, 12234, 12659, 12661,
        12738, 12740, 12789, 13069, 13078, 13144, 13333, 13403, 13657,
        13694, 13701, 14179, 14494, 14651, 14653, 14793, 14828, 15147,
        15292, 15361, 15519, 15592, 15643, 15743, 16260, 16390, 16463,
        16489, 16503, 16506, 16684, 16699, 16795, 16903, 17004, 17029,
        17118, 17135, 17148, 17168, 17206, 17208, 17343, 17654, 17678,
        17683, 17737, 17790, 17881, 17969, 18027, 18100, 18101, 18114,
      

In [38]:
X_train_np[0][39473]

1

In [40]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(X_train_cv,y_train)

MultinomialNB()

In [43]:
X_test_cv= v.transform(X_test)

In [45]:
from sklearn .metrics import classification_report 
y_pred=model.predict(X_test_cv)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.98      0.99      0.99       752
           1       0.98      0.96      0.97       283

    accuracy                           0.98      1035
   macro avg       0.98      0.97      0.98      1035
weighted avg       0.98      0.98      0.98      1035



In [46]:
emails=[
    'hey mohan,can we hang out together?',
    'UPTO 20% doscount on clothes ,dont miss it !'
]
emails_count=v.transform(emails)
model.predict(emails_count)

array([0, 1])

In [47]:
from sklearn.pipeline import Pipeline
clf=Pipeline([
    ('vectorizer',CountVectorizer()),
    ('nb',MultinomialNB())
])

In [48]:
clf.fit(X_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [51]:
y_pred=clf.predict(X_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.98      0.99      0.99       752
           1       0.98      0.96      0.97       283

    accuracy                           0.98      1035
   macro avg       0.98      0.97      0.98      1035
weighted avg       0.98      0.98      0.98      1035

